- name: Depoly grafana 
  hosts: grafana
  become: yes
  gather_facts: yes
 # Roles  
  roles:
    - grafana
  vars:
    slave_ip: 10.0.3.205
    graphana_version: 10.1.0
- name: Depoly graphite
  hosts: graphite
  become: yes
  gather_facts: yes
 # Roles
  roles:
    - graphite
- name: Depoly Collectd
  hosts: collectd
  become: yes
  gather_facts: yes
 # Roles
  roles:
    - collectd
  vars:
    virtual_ip: 192.168.122.20
    master_ip: 192.168.122.10
    slave_ip: 192.168.122.11
    interface: enp1s0
    interface2: enp1s0
    ip_graphite: 192.168.122.6
    ip_grafana: 192.168.122.5
    node1_ip: 192.168.122.10
    node2_ip: 192.168.122.11  




