- name: Depoly website
  hosts: keepalived
  become: yes
  gather_facts: yes
 # Roles  
  roles:
    - apache2
    - keepalived
  vars:
    virtual_ip: 192.168.122.20
    master_ip: 192.168.122.10
    slave_ip: 192.168.122.11
    interface: enp1s0
    interface2: enp1s0

